"""Stdlib-only preflight. Import/GPU probes run in bounded, disposable children.

No model weights are opened, downloaded or generated by this checker.
"""
import argparse
import importlib
import json
import os
from pathlib import Path
import platform
import subprocess
import sys
import tempfile

PACKAGES = ('torch', 'torchvision', 'transformers', 'diffusers', 'accelerate', 'PIL',
            'psutil', 'filelock', 'safetensors', 'huggingface_hub', 'numpy', 'tokenizers',
            'gguf', 'sdnq', 'peft', 'mlx', 'mlx_vlm')
LABELS = {'PIL': 'Pillow', 'huggingface_hub': 'Hugging Face Hub', 'mlx_vlm': 'MLX-VLM'}


def record(key, title, state, detail='', required=True):
    return dict(id=key, title=title, state=state, detail=detail, required=required)


def emit(value):
    print(json.dumps(value, ensure_ascii=False), flush=True)


def inspect_child(name):
    if name == 'dependencies':
        result=subprocess.run([sys.executable, '-m', 'pip', 'check'],capture_output=True,text=True,encoding='utf-8',errors='replace',timeout=45)
        if result.returncode: raise RuntimeError((result.stdout+'\n'+result.stderr).strip())
        return '依赖版本兼容'
    if name == 'pipeline':
        import inspect
        from diffusers import QwenImage21Pipeline, AutoencoderKLQwenImage21
        parameters = inspect.signature(QwenImage21Pipeline.__call__).parameters
        needed = {'prompt', 'image', 'width', 'height', 'num_inference_steps', 'callback_on_step_end', 'negative_prompt', 'true_cfg_scale', 'output_resolution', 'use_kv_cache'}
        if not needed.issubset(parameters):
            raise RuntimeError('当前 Diffusers 不支持所需的图像接口。')
        source=inspect.getsource(QwenImage21Pipeline._get_qwen_prompt_embeds)
        if 'norm.register_forward_hook' not in source:
            raise RuntimeError('当前文字编码接口与固定版本不一致，请修复环境。')
        # The staged pipeline (staged_pipeline.py) and the MPS VAE patch rely on these internals.
        from diffusers.models.autoencoders.autoencoder_kl_qwenimage21 import QwenImage21AvgDown3D
        from diffusers import QwenImage21Transformer2DModel
        if 'image_pad_mask' not in inspect.signature(QwenImage21Pipeline.encode_prompt).parameters or not hasattr(QwenImage21Pipeline,'_encode_vae_image') or not hasattr(QwenImage21Transformer2DModel,'from_single_file'):
            raise RuntimeError('当前文字编码接口与固定版本不一致，请修复环境。')
        return 'QwenImage21Pipeline / GGUF / staged encoding / MPS VAE patch'
    if name == 'enhancer':
        import mlx_vlm.models.qwen3_5  # noqa: F401  (PE-T2I / PE-I2I architecture)
        return 'MLX-VLM Qwen3.5 / PE-T2I / PE-I2I'
    if name == 'gpu':
        import torch
        if platform.system() == 'Darwin':
            if not torch.backends.mps.is_available():
                raise RuntimeError('未检测到可用的 Apple GPU。')
            device = 'mps'
            label = 'Apple Metal / MPS'
        else:
            if not torch.cuda.is_available():
                raise RuntimeError('未检测到可用的 NVIDIA CUDA GPU。')
            if not torch.cuda.is_bf16_supported():
                raise RuntimeError('当前显卡不支持模型所需的 BF16。')
            device = 'cuda'
            label = torch.cuda.get_device_name(0)
        # A few bytes confirm that the driver executes work. This is not model inference.
        for dtype in (torch.float16, torch.bfloat16):
            value = torch.ones((2, 2), device=device, dtype=dtype)
            if (value @ value).float().cpu().tolist() != [[2., 2.], [2., 2.]]:
                raise RuntimeError('GPU 基础运算检查失败。')
        return label
    module = importlib.import_module(name)
    if name in ('torch','transformers'):
        from packaging.version import Version
        minimum={'torch':'2.14.0','transformers':'5.17.0'}[name]
        if Version(module.__version__)<Version(minimum):raise RuntimeError(f'{name} >= {minimum} is required')
    return str(getattr(module, '__version__', '已安装'))


def run_child(name, timeout=60):
    result = subprocess.run([sys.executable, '-X', 'utf8', str(Path(__file__).resolve()), '--check', name],
        capture_output=True, text=True, encoding='utf-8', errors='replace', timeout=timeout,
        creationflags=getattr(subprocess, 'CREATE_NO_WINDOW', 0),
        env={**os.environ, 'HF_HUB_OFFLINE': '1', 'TRANSFORMERS_OFFLINE': '1',
             'HF_HUB_DISABLE_TELEMETRY': '1', 'PYTHONUTF8': '1'})
    lines = result.stdout.strip().splitlines()
    try:
        report = json.loads(lines[-1])
    except (ValueError, IndexError):
        raise RuntimeError('依赖检查进程退出，请尝试修复环境。')
    if result.returncode or not report.get('ok'):
        raise RuntimeError(report.get('error', '依赖无法加载。'))
    return report['detail']


def collect(data, check=run_child):
    """Yield each status change; failed checks never become successes by omission."""
    valid = (3, 10) <= sys.version_info[:2] < (3, 14) and sys.maxsize > 2**32
    yield record('python', 'Python 运行环境', 'pass' if valid else 'fail', platform.python_version() if valid else '需要 64 位 Python 3.10–3.13。')
    try:
        data.mkdir(parents=True, exist_ok=True)
        with tempfile.TemporaryFile(dir=data) as f:
            f.write(b'studio');f.flush()
        yield record('storage', '本地存储', 'pass', '可以保存会话与图片')
    except OSError:
        yield record('storage', '本地存储', 'fail', '无法写入数据目录，请检查磁盘和权限。')
    for name in (*PACKAGES, 'dependencies', 'pipeline', 'enhancer', 'gpu'):
        title = {'dependencies': '依赖完整性', 'pipeline': '图像推理接口', 'enhancer': '提示词增强接口', 'gpu': 'GPU 加速'}.get(name, LABELS.get(name, name))
        key = name if name in ('dependencies', 'pipeline', 'enhancer', 'gpu') else 'package:' + name
        yield record(key, title, 'checking', '正在检测…')
        try:
            detail = check(name)
            yield record(key, title, 'pass', detail)
        except subprocess.TimeoutExpired:
            yield record(key, title, 'fail', '检测超时，请重试或修复环境。')
        except Exception as error:
            # Keep upstream diagnostics visible in Details, not in the application copy.
            value = record(key, title, 'fail', '无法加载，请安装或修复依赖。')
            value['diagnostic'] = str(error)[:1500]
            yield value


def ready(items):
    required = [item for item in items.values() if item.get('required', True)]
    return bool(required) and all(item.get('state') == 'pass' for item in required)


def is_environment_error(error):
    text = str(error).lower()
    return any(fragment in text for fragment in ('no module named', 'cannot import name', 'dll load failed',
        '未检测到 gpu 加速', 'torch not compiled with cuda', 'cuda driver version is insufficient',
        'could not load library', 'no nvidia driver', 'not linked with support for mps', '未检测到可用的', '当前显卡不支持', '需要修复环境'))


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--data', type=Path)
    parser.add_argument('--check', choices=(*PACKAGES, 'dependencies', 'pipeline', 'enhancer', 'gpu'))
    options = parser.parse_args()
    if options.check:
        try:
            emit({'ok': True, 'detail': inspect_child(options.check)})
        except Exception as error:
            emit({'ok': False, 'error': str(error)[:1500]});sys.exit(1)
    else:
        if options.data is None: parser.error('--data is required')
        items = {}
        for item in collect(options.data):
            items[item['id']] = item;emit({'type': 'check', **item})
        emit({'type': 'complete', 'ready': ready(items)})
